import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { TriggerLab } from './store.svelte';
import { MemStorage } from '../test-support/mem-storage';
import { harnessClient, newHarness } from '../test-support/ws-harness';

/* INSTRUMENT (INIT-02 S1) — the store's public surface, pinned.
   Nothing else in the suite can tell you whether a refactor REMOVED a member, MOVED one, or
   quietly ADDED one; a green suite proves the members that are exercised still work, never that
   the set is the set you meant. This file is the arbiter for the whole store-decomposition
   initiative: every step that publishes a collaborator and deletes its forwarders must show up
   here as an exact removal/addition count, in the same commit as the change.

   How the inventory is taken: Svelte 5 compiles class `$state`/`$derived` fields to PROTOTYPE
   accessors, so the members do not all live on the instance — the surface is the union of
   `Object.getOwnPropertyNames(Object.getPrototypeOf(store))` (accessors + methods) and
   `Object.keys(store)` (plain own fields, including TS-`private` ones, which are private only
   at compile time). `constructor` and `_`-prefixed names are filtered out — so an added member
   that a probe wants this instrument to catch must NOT be `_`-prefixed (the plan's suggested
   `__probe` would be filtered out and prove nothing; `zzProbe` is what was used, and both the
   inventory and the LOC ratchet caught it).

   Hermetic BY ENFORCEMENT, not by hope: the default constructor builds a real WSClient and OPENS
   A SOCKET, which would make the one instrument this plan's parity evidence hangs off the
   flakiest test in the suite. So the injected harness client is not optional AND
   `globalThis.WebSocket` is poisoned to throw for the duration — if anyone ever makes the store
   dial out on construction, this file fails loudly instead of going flaky. localStorage is the
   shared MemStorage double, same beforeEach/afterEach pair as store.shows.test.ts. */

/** Ceiling on the member count. The store only shrinks from here — a step that publishes a
    collaborator deletes forwarders, so this ratchet never needs raising. */
const MEMBER_CAP = 381;
/** Ceiling on store.svelte.ts's line count. Same direction: down only. */
const LOC_CAP = 3507;

const EXPECTED_MEMBERS: string[] = [
  'acceptsMidiChannel',
  'activeSection',
  'activeSectionId',
  'activeShow',
  'activeShowId',
  'activeSong',
  'activeSongId',
  'addBand',
  'addGraphToSection',
  'addModInput',
  'addModifierNode',
  'addMonitor',
  'addNode',
  'addPlayNode',
  'addSongSection',
  'adoptController',
  'allCanvasScenes',
  'allPresets',
  'applyAuthored',
  'applyPreset',
  'applyRemapResult',
  'applyShow',
  'authFailCount',
  'authRequired',
  'autoWireEffectToOutput',
  'autosaveArmed',
  'availableModParams',
  'backups',
  'batchIntoCurrentUndo',
  'beat',
  'beatsPerBar',
  'blankFrame',
  'bootRecovery',
  'bpm',
  'buildPatchDoc',
  'busLevels',
  'busLevelsDisplay',
  'busOf',
  'buses',
  'canEdit',
  'canSplice',
  'canTakeover',
  'cancelMidiLearn',
  'cancelPasteFallback',
  'canvasEffects',
  'canvasSceneJson',
  'canvasScenes',
  'ccNodeChannel',
  'ccNodeController',
  'ccNodeLiveValue',
  'ccNodeSource',
  'changeKind',
  'clearMonitor',
  'clearServerError',
  'client',
  'clipMeta',
  'clipSources',
  'closeEnv',
  'closeGallery',
  'closeSettings',
  'closeShow',
  'closeSongPaste',
  'connect',
  'controllerCandidates',
  'controllerRecommendation',
  'controllerScanning',
  'controllerStatus',
  'controllerTest',
  'copyGraphToClipboard',
  'copyNode',
  'copyPatch',
  'copySection',
  'copySectionToClipboard',
  'copySongToClipboard',
  'createCanvasScene',
  'createGraph',
  'createSong',
  'deleteCanvasScene',
  'deleteGraph',
  'deleteLibrarySong',
  'deletePreset',
  'deleteShow',
  'detachSongReference',
  'disconnect',
  'discoverControllers',
  'dockVoices',
  'dockVoicesDisplay',
  'drums',
  'duplicateCanvasScene',
  'duplicateEffect',
  'duplicateGraph',
  'duplicateNode',
  'duplicatePreset',
  'duplicateSection',
  'duplicateSong',
  'editEdge',
  'editorLabel',
  'effectName',
  'effectOf',
  'effects',
  'effectsForScope',
  'enginePreviewLive',
  'engineSync',
  'engineTransportLive',
  'ensureValueDefaults',
  'envKind',
  'envTarget',
  'envelopeNodeAdsr',
  'envelopeNodeEnvelope',
  'errorCaptureUninstall',
  'exportSongToLibrary',
  'findResolvedSection',
  'finishPaste',
  'fireSectionGraph',
  'fireSeq',
  'flushOnUnload',
  'forwardMidi',
  'fps',
  'fpsLast',
  'freshEdgeId',
  'freshNodeId',
  'galleryBlock',
  'getEnvelope',
  'graphFireAt',
  'graphLabel',
  'graphLibrary',
  'graphNames',
  'graphs',
  'hit',
  'identifyController',
  'identifyHoop',
  'importSongReference',
  'inputActivity',
  'inputBadge',
  'isBindableCcController',
  'isBuiltinCanvasScene',
  'isEnveloped',
  'isViewer',
  'kitDrumInfos',
  'labModel',
  'last',
  'lastOscHeard',
  'lastSectionFire',
  'latencyMs',
  'lfoSettings',
  'link',
  'liveCcTable',
  'liveInput',
  'liveNodePositions',
  'liveNodeY',
  'liveOscTable',
  'liveParams',
  'mappedDrumIdForMidiNote',
  'mappingsFor',
  'markGraphFire',
  'materializePaste',
  'midi',
  'midiAvailable',
  'midiChannel',
  'midiDevices',
  'midiLearnTarget',
  'midiUnavailableReason',
  'modInputsOf',
  'modSourcesFor',
  'modTargetSpecs',
  'model',
  'monitor',
  'monitorDestinationFilter',
  'monitorEvents',
  'monitorForClientMessage',
  'monitorSeq',
  'monitorSourceFilter',
  'monitorTextFilter',
  'monitorTypeFilter',
  'moveGraphPlacement',
  'moveNode',
  'moveSection',
  'networkAdapters',
  'newShow',
  'nodeClipboard',
  'normalizeGraphs',
  'noteNodeChannel',
  'noteNodeLiveValue',
  'noteNodeMode',
  'noteNodeNumber',
  'noteNodeReleaseMs',
  'nowTick',
  'openEnv',
  'openGallery',
  'openSettings',
  'openShow',
  'openSongPaste',
  'oscHeardBadge',
  'oscListen',
  'oscNodeAddress',
  'oscNodeLiveValue',
  'output',
  'outputPacketsPerSec',
  'pads',
  'paneSizes',
  'pasteFallback',
  'pasteGraphFromClipboard',
  'pasteNode',
  'pasteSection',
  'pasteSectionFromClipboard',
  'pasteSong',
  'pasteSongText',
  'patchLabels',
  'persistDispose',
  'pickEffect',
  'placeClone',
  'playing',
  'presence',
  'presetById',
  'presetUsageCount',
  'presets',
  'presetsForEffect',
  'prevPacketSample',
  'previewFrame',
  'project',
  'pushUndoSnapshot',
  'raf',
  'randomDistribution',
  'randomSteps',
  'receiveInputEcho',
  'reconnect',
  'recordInputActivity',
  'refreshBackups',
  'remapBandPorts',
  'remapCtx',
  'removeBand',
  'removeGraphFromSection',
  'removeModInput',
  'removeNode',
  'removeSection',
  'removeSong',
  'removeSongReference',
  'renameCanvasScene',
  'renameEffect',
  'renameGraph',
  'renameLibrarySong',
  'renamePreset',
  'renameSection',
  'renameShow',
  'renameSong',
  'reportError',
  'requestNetworkAdapters',
  'resetAuthoredToSeed',
  'resetMonitorFilters',
  'resolveHitGraphsLocal',
  'resolvedSongs',
  'resolvedView',
  'restoreBackup',
  'restoringUndo',
  'role',
  'runUndoable',
  'saveNodeAsPreset',
  'saveShow',
  'saveShowAs',
  'saveStatus',
  'saveStatusCtl',
  'saveTimer',
  'scheduleSave',
  'sectionClipboard',
  'sections',
  'sectionsCtl',
  'selectGraphInSection',
  'selectPreset',
  'selectableEffects',
  'selectedGraph',
  'selectedGraphFireAt',
  'selectedPad',
  'selectedPadKey',
  'serverError',
  'serverFrame',
  'serverModel',
  'serverVoices',
  'setActiveSection',
  'setActiveSong',
  'setBandCutoff',
  'setBus',
  'setCanvasScene',
  'setCcChannel',
  'setCcController',
  'setCcNodeSource',
  'setChance',
  'setControllerAuth',
  'setCrossfade',
  'setDelayMode',
  'setDelayMs',
  'setDivision',
  'setDrumTransform',
  'setEnvAdsr',
  'setEnvAmount',
  'setEnvKind',
  'setEnvPoints',
  'setEnvelopeNodeAdsr',
  'setHoopConfig',
  'setInputMap',
  'setInvert',
  'setKitGlobal',
  'setLfo',
  'setLiveNodePosition',
  'setLook',
  'setMappingAmount',
  'setMappingInvert',
  'setMappingRange',
  'setMidiChannel',
  'setMixBlendMode',
  'setMixEdgeOpacity',
  'setMode',
  'setModifierBypass',
  'setModifierId',
  'setMonitorDestinationFilter',
  'setMonitorSourceFilter',
  'setMonitorTextFilter',
  'setMonitorTypeFilter',
  'setNoRepeat',
  'setNodeLayout',
  'setNoteNodeChannel',
  'setNoteNodeMode',
  'setNoteNodeNumber',
  'setNoteNodeReleaseMs',
  'setOscNodeAddress',
  'setOutput',
  'setParam',
  'setPatchLabel',
  'setPolyphony',
  'setProjectPatch',
  'setRandomDistribution',
  'setRandomSteps',
  'setRouting',
  'setScope',
  'setSectionGraphs',
  'setSharing',
  'setSwitchOn',
  'setTargetId',
  'setThreshold',
  'setTriggerSource',
  'setValueMode',
  'settingsBlock',
  'showSource',
  'shows',
  'showsCtl',
  'showsUsingSong',
  'songLibrary',
  'songLibraryList',
  'songPasteOpen',
  'songRefs',
  'songs',
  'sourceDrumIdForTriggerSource',
  'spliceOnDrop',
  'start',
  'startAutosave',
  'startMidiLearn',
  'stop',
  'stopAutosave',
  'stripBandPorts',
  'submitPasteFallback',
  'submitPin',
  'suppressUndoSnapshot',
  'syncShowToServer',
  'syncTransport',
  'takeover',
  'tickDockDisplay',
  'timeMs',
  'toAuthored',
  'togglePlay',
  'triggerSource',
  'tunnel',
  'undo',
  'undoLimit',
  'undoStack',
  'updateCanvasSceneJson',
  'useServer',
  'velocity',
  'visibleMonitorEvents',
  'voiceLevelDisplay',
  'watchController',
  'wireClient',
  'writeClip',
];

function surfaceOf(o: object): string[] {
  return [
    ...new Set([...Object.getOwnPropertyNames(Object.getPrototypeOf(o)), ...Object.keys(o)]),
  ]
    .filter((n) => n !== 'constructor' && !n.startsWith('_'))
    .sort();
}

function newStore(): TriggerLab {
  return new TriggerLab(harnessClient(newHarness()));
}

let realWebSocket: unknown;

beforeEach(() => {
  (globalThis as { localStorage?: Storage }).localStorage = new MemStorage() as unknown as Storage;
  realWebSocket = (globalThis as { WebSocket?: unknown }).WebSocket;
  (globalThis as { WebSocket?: unknown }).WebSocket = function poisoned(): never {
    throw new Error('store.surface.test.ts must not open a socket — the fake client is not optional');
  };
});
afterEach(() => {
  delete (globalThis as { localStorage?: Storage }).localStorage;
  (globalThis as { WebSocket?: unknown }).WebSocket = realWebSocket;
});

describe('store public surface', () => {
  it('is exactly the checked-in member inventory', () => {
    expect(surfaceOf(newStore())).toEqual(EXPECTED_MEMBERS);
  });

  it('stays under the member ratchet', () => {
    expect(EXPECTED_MEMBERS.length).toBeLessThanOrEqual(MEMBER_CAP);
  });

  it('keeps store.svelte.ts under the LOC ratchet', () => {
    const loc = readFileSync(new URL('./store.svelte.ts', import.meta.url), 'utf8').split('\n')
      .length;
    expect(loc).toBeLessThanOrEqual(LOC_CAP);
  });
});
